spring.application.name=springSecurity

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/springsecuritydb
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect