spring.application.name=springSecurity
spring.datasource.url=jdbc:mysql://localhost:3306/springSecurityDb
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Show SQL queries
spring.jpa.properties.hibernate.format_sql=true

# Highlight SQL (colored output in console)
spring.jpa.properties.hibernate.highlight_sql=true

#Spring Security Config
#spring.security.user.name=smit
#spring.security.user.password=1234
##spring.security.user.

jwt.secretKey = adjkabfjkbj3423423nasdnajnalsndalsndaslndas23423njnjln423jln423n423kn42jkn4jkn