spring.application.name=springSecurity
spring.data.mongodb.uri=mongodb://admin:gPv8BCebzwaW2rhn@ac-wifek0l-shard-00-00.wofwskr.mongodb.net:27017,ac-wifek0l-shard-00-01.wofwskr.mongodb.net:27017,ac-wifek0l-shard-00-02.wofwskr.mongodb.net:27017/smit-db?ssl=true&replicaSet=atlas-nwpx5m-shard-0&authSource=admin&retryWrites=true&w=majority
